image: gitpod/workspace-mysql

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - gabrielbb.vscode-lombok
    - vmware.vscode-spring-boot
    # Adicione outras extensões necessárias aqui

ports:
  - 8080

tasks:
  - name: Start Spring Boot API
    init: mvn clean install
    command: mvn spring-boot:run
    ports:
      - 8080
