image: ubuntu

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - gabrielbb.vscode-lombok
    - vmware.vscode-spring-boot
    # Adicione outras extensões necessárias aqui

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y default-jdk maven
    command: echo "Java and Maven installed."
