image: gitpod/workspace-full

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - gabrielbb.vscode-lombok
    - vmware.vscode-spring-boot
    - Pleiades.java-extension-pack-jdk
    - eamodio.gitlens
    - mtxr.sqltools
    - mtxr.sqltools-driver-mysql
    # Adicione outras extensões necessárias aqui

tasks:
  - name: Start Spring Boot API
    init: pwd
    command: sdk install java 17.0.8.fx-zulu; sdk default java 17.0.8.fx-zulu; /workspace/gestaoRecursosConselho/api-conselho/mvnw spring-boot:run