image: gitpod/workspace-full

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - gabrielbb.vscode-lombok
    - vmware.vscode-spring-boot
    - Pleiades.java-extension-pack-jdk
    - eamodio.gitlens
    - mtxr.sqltools
    - mtxr.sqltools-driver-mysql
    # Adicione outras extensões necessárias aqui

tasks:
  - name: Start Spring Boot API
    init: pwd
    command: cd /workspace/gestaoRecursosConselho; /usr/bin/env /home/gitpod/.sdkman/candidates/java/17.0.8.fx-zulu/bin/java @./gitpod_args br.eti.davinunes.apiconselho.ApiConselhoApplication
