---
image: ubuntu
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - gabrielbb.vscode-lombok
    - vmware.vscode-spring-boot
ports:
  - 8080
tasks:
  - name: Install Java and Maven
    init: |
      sudo apt-get update
      sudo apt-get install -y default-jdk maven
    command: echo "Java and Maven installed."
  - name: Start Spring Boot API
    command: mvn spring-boot:run
    init: mvn clean install
    ports:
      - 8080
